version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: basketball-frontend
    ports:
      - "8080:8080"
    networks:
      - basketball-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: basketball-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - basketball-network

networks:
  basketball-network:
    driver: bridge