version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge