version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"  # Explicitly define server ports
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
    name: basketball_network