version: '3'
services:
  client:
    build: ./client
    restart: always

  server:
    build: ./server
    restart: always
    environment:
      - PORT=5000
    expose:
      - 5000

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
